### PR TITLE
Prepare /usr versions of remaining binaries (boo#1029961)

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by mgerstner** [comment]
We're postponing your PR# a bit, because we are thinking about introducing a mechanism to avoid redundancy in permissions profile in cases like this.

Can you point us to some tracker bug regarding this change of /sbin to /usr/sbin? How is the change performed, individually per package?

**Comment by lnussel** [comment]
This is part of the generic usrmerge as discussed in https://bugzilla.suse.com/show_bug.cgi?id=1029961

Of course we could do this on an individual basis but as we can see from the last eight years that leads to nowhere. So currently I'm trying to get this all at once. The plan is not finally approved, I'm still figuring out the corner cases before putting it up for discussion. Meanwhile if we could just make sure permissions are not in the way that would be one less problem to worry about. Nothing bad happens if we add the /usr entries already.

**Comment by mgerstner** [comment]
Thanks for the explanation. I opened PR #106 to add the compatibility entries you want using the new variable feature we implemented. Then things will be cleaner, the libexec move already created quite some chaos that I'd like to avoid another time.

**Comment by mgerstner** [comment]
PR #106 is merged by now. Compatibility entries are now in place. Therefore closing your PR.

**Pull request closed without merging**
