### PR TITLE
Add permissions for the permission files themselves

### PR DESCRIPTION
**Pull request by andreasstieger**

### CODE REVIEW

**Comment by lnussel** [comment]
what for? they are not meant to change

**Comment by andreasstieger** [comment]
To check that they were not set to world readable by someone

**Comment by lnussel** [comment]
they are world readable and distro provided so not secret at all

Add remove entries there, don't add more please :)

**Comment by andreasstieger** [comment]
Obviously meant... not world writable

**Comment by andreasstieger** [comment]
So which issue do you see with having these entries in there?

**Comment by lnussel** [comment]
It's just superfluous. Duplicates information that are in rpms anyways. I've never heard of a case where someone accidentally changed /etc/permissions permissions. So if we wanted to guard against such cases where to stop?
I'd rather move the static files to /usr to make it crystal clear that those are read-only.

**Comment by mgerstner** [comment]
Considering that the possibly world-writeable permissions files should heal themselves this way doesn't really make to much sense. Getting notified about bad permissions is also possible via `rpm -V`. As Ludwig says it's difficult to tell where to stop such a self-healing feature. Therefore lets close this.

**Pull request closed without merging**
