### PR TITLE
Libexec update

### PR DESCRIPTION
**Pull request by gmbr3**
bsc#1171164

### CODE REVIEW

**Comment by mgerstner** [comment]
Thank you for your efforts. Can you please explain the situation regarding virtualbox? Your commit fixes the paths to /usr/lib again. Can these binaries not be moved?

**Comment by gmbr3** [comment]
Changed my mind thinking about it. Can't be /usr/libexec because shared objects but it probably should be /usr/lib64 due to 64bit linking. I'll update when ready.

**Comment by mgerstner** [comment]
I still don't understand the restriction. Which libraries do come into play here? The paths in the profile all point to executables it seems.

**Comment by gmbr3** [comment]
old

**Pull request closed without merging**
